project:
  type: book

book:
  title: "SNT - Somalia - 2023"
  author: "Chunzhe, Spencer, ZHANG"
  date: "3/7/2023"
  chapters:
    - index.qmd
    - part: "Data Management"
      chapters:
        - load_data.qmd
        - description.qmd
        - missing_data.qmd
        - data_checking.qmd
        - duplicates.qmd
        - outliers.qmd
        - report_status.qmd
        - interrelationships.qmd
    - part: "Analysis"
      chapters:
        - adjusted_incidence.qmd
        - care_seeking.qmd
        - llins.qmd
        - epi.qmd
    - intro.qmd
    - summary.qmd
  appendices:
    - references.qmd
    - list_of_figures_and_tables.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: Simplex
      dark: Cyborg
    html-math-method: katex
    code-fold: true
    code-tools: true
    code-link: true
    highlight-style: gruvbox
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: true

title-block-banner: true
editor: visual
toc: true
number-sections: true
highlight-style: pygments
execute:
  cache: true
