default:
  country: nigeria
  dirs:
    data: _data
    functions: _functions
    handmade: handmade
    database: database
    reports: reports
    logs: logs
  clean_before_new_analysis:
    - database
    - reports
    - logs
  db:
   package: RSQLite
   dbconnect: SQLite
   dbname: ":memory:"
  cores: 8
